### ISSUE TITLE
streamline evaluation script

### ISSUE THREAD

**Issue by FabianIsensee** [xmed-lab/TriALS#2]
The current [evaluation code](https://github.com/xmed-lab/TriALS/tree/main/evaluation) seems highly specific and tailored for your repository. It's all in one large script, which makes it difficult to apply it for unrelated algorithms. It could be useful for participants to wrap it into functions that they can call themselves, for example:

`evaluate_folder(folder_with_gt_files, folder_with_pred_files)`
`evaluate_case(pred_file, gt_file)`

This should be quite doable in the existing script. The script can then just use these functions.

Best,
Fabian

**Comment by marwankefah** [comment]
Hi Fabian,

I agree with you. I have only copied the LiTs evaluation [script](https://github.com/PatrickChrist/lits-challenge-scoring/blob/master/program/evaluate.py), but I will wrap it for better usability.

Thank you for bringing this to my attention,

Marawan Elbatel

**Comment by marwankefah** [comment]
Hi Fabian,

Apologies for the late response, I’ve refactored the [evaluation code](https://github.com/xmed-lab/TriALS/tree/main/eval_scripts). Participants can now easily run the script on their folders, improving its usability.

Let me know if you have any further feedback.

Thank you,
Marawan Elbatel

**Comment by FabianIsensee** [comment]
Thanks a lot!!
